#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.1
#  in conjunction with Tcl version 8.6
#    Mar 30, 2022 08:17:33 PM -03  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import snowpois0n_support

class Snowpois0n:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("470x619+443+60")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1,  1)
        top.title("Snowpois0n Jailbreak")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top

        self.Button1 = tk.Button(self.top)
        self.Button1.place(relx=0.298, rely=0.501, height=44, width=197)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#ffffff")
        self.Button1.configure(background="#b1b1b1")
        self.Button1.configure(command=snowpois0n_support.jailbreak)
        self.Button1.configure(compound='left')
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Segoe UI} -size 12")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#727272")
        self.Button1.configure(highlightcolor="#0b0b57")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Jailbreak''')

        self.Button1_1 = tk.Button(self.top)
        self.Button1_1.place(relx=0.298, rely=0.729, height=44, width=197)
        self.Button1_1.configure(activebackground="#ececec")
        self.Button1_1.configure(activeforeground="#000000")
        self.Button1_1.configure(background="#b1b1b1")
        self.Button1_1.configure(command=snowpois0n_support.fastboot)
        self.Button1_1.configure(compound='left')
        self.Button1_1.configure(disabledforeground="#a3a3a3")
        self.Button1_1.configure(font="-family {Segoe UI} -size 12")
        self.Button1_1.configure(foreground="#000000")
        self.Button1_1.configure(highlightbackground="#d9d9d9")
        self.Button1_1.configure(highlightcolor="black")
        self.Button1_1.configure(pady="0")
        self.Button1_1.configure(text='''Fastboot Mode''')

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.106, rely=-0.048, height=340, width=447)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 12")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(justify='left')
        self.Label1.configure(text='''Welcome to Snowpois0n version 0.3, click on "Jailbreak"
to start jailbreaking your Android Device running
Android 4.2 until Android 10. Please enable Developer
Mode and USB Sharing before start Jailbreaking,
do not forget to enable Flight Mode and remove
passcode. After Jailbroken, click on "Reboot Device".

Otherwise, if you want to boot your device into
fastboot mode, press "Fastboot Mode" button.
You can use Fastboot Mode to enter inside the
Android recovery menu.''')

        self.Label2 = tk.Label(self.top)
        self.Label2.place(relx=0.281, rely=0.821, height=76, width=243)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(anchor='w')
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(compound='left')
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Arial} -size 11")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Copyright (C) Gabriel Margarido
2022''')

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Button1_2 = tk.Button(self.top)
        self.Button1_2.place(relx=0.298, rely=0.614, height=44, width=197)
        self.Button1_2.configure(activebackground="#ececec")
        self.Button1_2.configure(activeforeground="#ffffff")
        self.Button1_2.configure(background="#b1b1b1")
        self.Button1_2.configure(command=snowpois0n_support.reboot_device)
        self.Button1_2.configure(compound='left')
        self.Button1_2.configure(disabledforeground="#a3a3a3")
        self.Button1_2.configure(font="-family {Segoe UI} -size 12")
        self.Button1_2.configure(foreground="#000000")
        self.Button1_2.configure(highlightbackground="#727272")
        self.Button1_2.configure(highlightcolor="#0b0b57")
        self.Button1_2.configure(pady="0")
        self.Button1_2.configure(text='''Reboot Device''')

def start_up():
    snowpois0n_support.main()

if __name__ == '__main__':
    snowpois0n_support.main()




